apiRules:
  - include:
      uidRegex: ^com.ai.behavior-tree/.Runtime/.BT
      type: Namespace
  - include:
      uidRegex: ^com.ai.behavior-tree/.Runtime/.BT.Runtime
      type: Namespace
  - exclude:
      uidRegex: .*
      type: Namespace
