apiRules:
  - include:
      uidRegex: .Runtime/.BT
      type: Namespace
  - include:
      uidRegex: .Runtime/.BT.Runtime
      type: Namespace
  - exclude:
      uidRegex: .*
      type: Namespace
