
name: Geneate Docfx documentation

on:
    push:
      branches: ["main"]

    workflow_dispatch:

jobs:
        publish-docs:
          runs-on: ubuntu-latest
          steps:
          # Install/update dotnet.
          - name: Checkout
            uses: actions/checkout@v3
          - name: Dotnet Setup
            uses: actions/setup-dotnet@v3
            with:
              dotnet-version: 7.x
          # Generate documentation.
          - run: dotnet tool update -g docfx
          - run: docfx Documentation/docfx.json

          # Push documentation to github page.
          - run: git config --global user.email "bot.github@github.io"
          - run: git add Documentation/_site/*
          - run: git commit -m "Updated website documentation"
          - run: git push origin main:gh-pages

      
          

