name: Geneate Docfx documentation

on:
    
    workflow_dispatch:

jobs:
        generate-docs:
          runs-on: ubuntu-latest
          steps:
          - name: Checkout
            uses: actions/checkout@v3

          # Install/update dotnet.
          - name: Dotnet Setup
            uses: actions/setup-dotnet@v3
            with:
              dotnet-version: 7.x

          # Generate documentation.
          - run: dotnet tool update -g docfx
          - run: docfx Documentation/docfx.json
           
          # Push documentation to github page.
          - name: Update documentation
            run: |
              git config --global user.name 'MikeBrixia'
              git config --global user.email 'MikeBrixia@users.noreply.github.com'
              git commit -am "Save local changes"
              git checkout -B gh-pages
              git add -f Documentation/_site/*
              git commit -am "Rebuild website"
              git filter-branch -f --prune-empty --subdirectory-filter Documentation/_site/ && git push -f origin gh-pages && git checkout main
              