
name: Geneate Docfx documentation

on:
    push:
      branches: ["main"]

    workflow_dispatch:

jobs:
        publish-docs:
          runs-on: ubuntu-latest
          steps:
          # Install/update dotnet.
          - name: Checkout
            uses: actions/checkout@v3
          - name: Dotnet Setup
            uses: actions/setup-dotnet@v3
            with:
              dotnet-version: 7.x
          # Generate documentation.
          - run: dotnet tool update -g docfx
          - run: docfx Documentation/docfx.json
          # Push documentation to github page.
          - name: Update documentation
            run: |
              git config --global user.name 'Bot'
              git config --global user.email 'Bot@users.noreply.github.com'
              git add Documentation/_site/*
              git commit -am "Automated documentation update"
              git push origin main:gh-pages

      
          

