name: Geneate Docfx documentation

on:
    
    workflow_dispatch:

jobs:
        generate-docs:
          runs-on: ubuntu-latest
          steps:
          - name: Checkout
            uses: actions/checkout@v3
          
          - name: Setup user config
            run: |
              git config --global user.name 'MikeBrixia'
              git config --global user.email 'MikeBrixia@users.noreply.github.com'
          
          # Clean documentation folder to free space for updated docs.
          - name: Clean previously generated documentation
            run: |
              git fetch origin gh-pages
              git checkout gh-pages
              git rm -r --ignore-unmatch Documentation/
              git add --all
              git commit -m 'Clean outdated documentation' --allow-empty
              git push origin gh-pages
              git ls-tree -r --name-only gh-pages
              git checkout main 
              
          # Install/update dotnet.
          - name: Dotnet Setup
            uses: actions/setup-dotnet@v3
            with:
              dotnet-version: 7.x

          # Generate documentation.
          - run: dotnet tool update -g docfx
          - run: |
              cd Documentation/
              docfx Documentation/docfx.json
           
          # Update the documentation.
          - name: Update documentation
            run: |
              git status
              git add --all
              git checkout gh-pages
              git commit -m 'Automated documentation update'
              git fetch origin gh-pages
              git pull --rebase origin gh-pages
              git push origin gh-pages
              