name: Geneate Docfx documentation

on:
    push:
        branches: ["main"]

    workflow_dispatch:

jobs:
    generate-docs:
        runs-on: ubuntu-latest
        steps:
        # Install dotnet
         - name: Checkout
           uses: actions/checkout@v4
         - name: Install dotnet
           uses: actions/setup-dotnet@v3
           with:
            dotnet-version: 7.x
        # Install and intialize docfx
         - name: Install docfx
           run: dotnet tool install -g docfx
        # generate API documentation
         - name: Build documentation
           run: docfx docfx.json
           continue-on-error: false
